// Generates public/wall.svg: one seamless unit of glossy subway tile in running bond.
// Deterministic (seeded), so the wall is identical on every build. Geometry only, no raster.
// Run: node scripts/make-wall.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, "..", "public", "wall.svg");

const TILE_W = 96;
const TILE_H = 48;
const GROUT = 3;
const COLS = 10; // unit width 960
const ROWS = 20; // unit height 960 (even, so the bond continues across the seam)
const W = COLS * TILE_W;
const H = ROWS * TILE_H;

// Glaze: deep teal-green, #145646 = hsl(165, 62%, 21%).
const BASE = { h: 165, s: 62, l: 21 };
const GROUT_FILL = "#0d3f33";

function mulberry32(seed) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(0x5a11e7);
const jitter = (amt) => (rand() * 2 - 1) * amt;

function tone() {
  // Handmade variation: mostly subtle, occasionally a darker or lighter firing.
  const roll = rand();
  const extra = roll < 0.08 ? -1.6 : roll > 0.94 ? 1.4 : 0;
  const h = BASE.h + jitter(2.5);
  const s = BASE.s + jitter(5);
  const l = BASE.l + jitter(1.6) + extra;
  return `hsl(${h.toFixed(1)} ${s.toFixed(1)}% ${l.toFixed(1)}%)`;
}

const speculars = [
  { cx: 0.22, cy: 0.18 },
  { cx: 0.7, cy: 0.22 },
  { cx: 0.42, cy: 0.12 },
  { cx: 0.86, cy: 0.3 },
];

const defs = `
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#fff" stop-opacity="0.1"/>
      <stop offset="0.16" stop-color="#fff" stop-opacity="0.045"/>
      <stop offset="0.55" stop-color="#fff" stop-opacity="0"/>
      <stop offset="0.9" stop-color="#000" stop-opacity="0.08"/>
      <stop offset="1" stop-color="#000" stop-opacity="0.16"/>
    </linearGradient>
    ${speculars
      .map(
        (s, i) => `<radialGradient id="s${i}" cx="${s.cx}" cy="${s.cy}" r="0.55">
      <stop offset="0" stop-color="#fff" stop-opacity="0.075"/>
      <stop offset="1" stop-color="#fff" stop-opacity="0"/>
    </radialGradient>`,
      )
      .join("\n    ")}
  </defs>`;

const rows = [];
for (let r = 0; r < ROWS; r++) {
  const offset = r % 2 ? TILE_W / 2 : 0;
  const count = offset ? COLS + 1 : COLS;
  const y = r * TILE_H;
  const colors = Array.from({ length: offset ? COLS : COLS }, () => tone());
  const spec = Array.from({ length: COLS }, () => Math.floor(rand() * speculars.length));
  for (let k = 0; k < count; k++) {
    const x = k * TILE_W - offset;
    // In an offset row the first and last partial tiles are the same wrapped tile.
    const idx = offset ? (k === count - 1 ? 0 : k) : k;
    const fill = colors[idx % colors.length];
    const s = spec[idx % spec.length];
    const rx = 2.5;
    const tx = (x + GROUT / 2).toFixed(1);
    const ty = (y + GROUT / 2).toFixed(1);
    const tw = TILE_W - GROUT;
    const th = TILE_H - GROUT;
    rows.push(
      `<g transform="translate(${tx} ${ty})"><rect width="${tw}" height="${th}" rx="${rx}" fill="${fill}"/><rect width="${tw}" height="${th}" rx="${rx}" fill="url(#g)"/><rect width="${tw}" height="${th}" rx="${rx}" fill="url(#s${s})"/></g>`,
    );
  }
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <!-- Provenance: generated by web/scripts/make-wall.mjs (seed 0x5a11e7). Authored geometry, no raster. -->
  ${defs}
  <rect width="${W}" height="${H}" fill="${GROUT_FILL}"/>
  ${rows.join("\n  ")}
</svg>
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, svg);
console.log(`wrote ${path.relative(process.cwd(), out)} (${(svg.length / 1024).toFixed(1)} KB, ${rows.length} tiles)`);
